<a href="https://colab.research.google.com/github/Abhilash-abhi666/Python-codes/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
#1  Define a dictionary ”cuboid” as follows: keys: [Length, Breadth, Height, Color], values: values for each key will be stored in lists. Initialize the values for each key as empty lists.
Populate this dictionary with 10 random cuboids.
Convert this dictionary to dataframe using pandas package in python. Export the dataframe as csv.
Open the csv file to verify
```



In [7]:
import numpy as np
import pandas as pd

In [8]:
cuboid = {"Length":[], "Breadth":[], "Height":[], "Color":[]}

In [9]:
cuboid["Length"]=1
for i in cuboid:
  cuboid[i]=np.random.randint(100,size=10)
  print(cuboid[i])


[15 65 98 65 72 31 29 94 62 19]
[74 95 63 59 91 23 77 59 55 77]
[31 89 63 72 26 66 46 19 41 42]
[47 59 98  4 64 92 43 37 65  4]


In [10]:
df=pd.DataFrame(data=cuboid)
df


Length  Breadth  Height  Color
0      15       74      31     47
1      65       95      89     59
2      98       63      63     98
3      65       59      72      4
4      72       91      26     64
5      31       23      66     92
6      29       77      46     43
7      94       59      19     37
8      62       55      41     65
9      19       77      42      4

In [19]:
df.to_csv('cuboid_file.csv', sep=',', index=False)

In [21]:
df1 = pd.read_csv('cuboid_file.csv')
print(df1)

   Length  Breadth  Height  Color
0      15       74      31     47
1      65       95      89     59
2      98       63      63     98
3      65       59      72      4
4      72       91      26     64
5      31       23      66     92
6      29       77      46     43
7      94       59      19     37
8      62       55      41     65
9      19       77      42      4
