<a href="https://colab.research.google.com/github/Abhilash-abhi666/Python-codes/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd

In [20]:
cuboid = {"Length":[], "Breadth":[], "Height":[], "Color":[]}

In [21]:
cuboid["Length"]=1
for i in cuboid:
  cuboid[i]=np.random.randint(100,size=10)
  print(cuboid[i])


[82 45 62 77 66 50 61 15 91 91]
[12 26 13  3  6  5 34 89 31 44]
[40 43 98 12 54 77 36 75 75 48]
[78  3 29 62 63 39 49  1 93 78]


In [24]:
df=pd.DataFrame(data=cuboid)
df

Length  Breadth  Height  Color
0      82       12      40     78
1      45       26      43      3
2      62       13      98     29
3      77        3      12     62
4      66        6      54     63
5      50        5      77     39
6      61       34      36     49
7      15       89      75      1
8      91       31      75     93
9      91       44      48     78